In [1]:
## 1. Create a ndarray of first five multiples of 6

import numpy as np
arr = np.array([6,12,18,24,30])
print(arr)

[ 6 12 18 24 30]


In [3]:
## 2. Convert the 1D array created in Q1 to 3D, and display the number of dimensions of the latter

arr_1 = np.array([[[6,12,18,24,30]]])
print("Array: ", arr_1)
print("Dimensions of array: ", arr_1.ndim)

Array:  [[[ 6 12 18 24 30]]]
Dimensions of array:  3


In [4]:
## Alternative solution to Q2

arr_1 = np.array([6,12,18,24,30], ndmin=3)
print("Array: ", arr_1)
print("Dimensions of array: ", arr_1.ndim)

Array:  [[[ 6 12 18 24 30]]]
Dimensions of array:  3


In [5]:
## 3. Create a 2D array where first 5 prime numbers occupy the 1st dimension and the first 5 composite numbers in the 2nd dimension

arr_2 = np.array([[2,3,5,7,11],[4,6,8,9,10]])
print(arr_2)

[[ 2  3  5  7 11]
 [ 4  6  8  9 10]]


In [6]:
## 4. From the array created in Q3, retrieve the last element from 2nd dimension

print(arr_2[1,-1])

10


In [7]:
## 5. Retrieve the 2nd, 3rd and 4th elements from both dimensions of the 2D array created in Q3

print(arr_2[0:2, 1:4])

[[3 5 7]
 [6 8 9]]


In [8]:
## 6. Display the data type of the array created in Q1, and change it to float

arr = np.array([6,12,18,24,30])
print(arr.dtype)

int32


In [9]:
new_arr = arr.astype(float)
print(new_arr)

[ 6. 12. 18. 24. 30.]


In [11]:
## 7. Create a 1D array of twelve zeros and reshape it to a 2D array of shape (3,4)

arr = np.zeros(12)
print("1D array of zeros: ", arr)
new_arr = arr.reshape(3,4)
print("2D array of zeros: \n", new_arr)

1D array of zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
## 8. Flatten the 2D array that you created in the previous question back to 1D

arr_1d = new_arr.reshape(-1)
print(arr_1d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
## 9. Consider an array [24,45,67,90,123,367]. Find the indexes where the values are even

arr = np.array([24,45,67,90,123,367])
a = np.where(arr%2 == 0)
print(a)

(array([0, 3], dtype=int64),)


In [14]:
## 10. Create two arrays, one with first 5 odd numbers and the other with first 5 even numbers. 
##     Then concatenate both the arrays along columns

arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
arr3 = np.vstack((arr1,arr2))
print(arr3)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [15]:
## 11. Subtract the even number array from the odd number array created in Q10

arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
arr3 = np.subtract(arr1,arr2)
print(arr3)

[-1 -1 -1 -1 -1]


In [16]:
## 12. Create two matrices of the squares and cubes of first 4 natural numbers, and perform matrix multiplication. 
##     Also, obtain the transpose of the matrix resulting from the multiplication

arr1 = np.array([[1,4],[9,16]])
arr2 = np.array([[1,8],[27,64]])
arr3 = np.dot(arr1,arr2)
print("Matrix multiplication: \n", arr3)
print("Transpose: \n", arr3.T)                                    # alternatively, arr3.transpose()

Matrix multiplication: 
 [[ 109  264]
 [ 441 1096]]
Transpose: 
 [[ 109  441]
 [ 264 1096]]


In [17]:
## end of notebook